export const BaseIcons = [
    'cart',
    'facebook',
    'instagram',
    'tiktok',
    'user',
    'settings',
    'logout',
    'delete',
    'cart-checkout',
    'search',
    'laptops-computers',
    'smartphones',
    'tv-electronics',
    'gaming',
    'home',
];